config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'

  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create # Allows creating only of comments
    resources :photos, only: :create   # Allows uploading ("creating") only of photos
  end
  resources :users, only: :show  # Allows showing only of users(?)

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'One Star'    => '1_star',
    'Two Stars'   => '2_stars',
    'Three Stars' => '3_stars',
    'Four Stars'  => '4_stars',
    'Five Stars'  => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
end

app/models/imagebuild.rb
class Image
  # belongs_to :user
  # has_many :comments
  # has_many :photos
  
  # geocoded_by :address
  # after_validation :geocode
  
  # validates :name, :presence => true, :length => { minimum: 6 }
  # validates :address, presence: true
  # validates :description, presence: true

  def initialize(image)
    @image = image  # Stores 'image' for later use, makes @image part of each instance of Image
  end

  def output_image  # No need for (argument) at end of method name
    @image.each do |row|
      puts row.join(" ")
    end
  end

end

image = Image.new([
      [0, 0, 0, 0],
      [0, 1, 0, 0],
      [0, 0, 0, 1],
      [0, 0, 0, 0]
    ])
image.output_image

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :photos
  
  geocoded_by :address
  after_validation :geocode
  
  validates :name, :presence => true, :length => { minimum: 6 }
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

    def create
       @place = Place.find(params[:place_id])
       @place.photos.create(photo_params)
       redirect_to place_path(@place) # Redirects visitor to the place's page after submitting form.  
    end
    
    private

    def photo_params
      params.require(:photo).permit(:picture, :caption)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index   # Displays 'place' records (10 per page) on 'root' page(s)
    @places = Place.order("created_at ASC").page(params[:page]).per(10)
  end

  def new   # Creates a new database record based on data the visitor submitted
    @place = Place.new
  end

  def create   
    @place = current_user.places.create(place_params) # Sends visitor's form submission to the database.
    if @place.valid?
      redirect_to root_path  # Redirects visitor to Home page after submitting form.  
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'You are Not Allowed to Edit this Page', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'You are Not Allowed to Edit this Page', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'You are Not Allowed to Delete this Place', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params   # Pulls submitted name, description and address values from the form.
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])  # Takes user id# from URL, puts that user's info into @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <link href="https://fonts.googleapis.com/css?family=Domine" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link</a></li>-->
        <li><%= link_to new_place_path do %>
          <i class="glyphicon glyphicon-plus-sign"></i>
          New Place
        <% end %>
        </li>
      </ul>
        <!---Hiding first of two dropdowns in nav bar:
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>-->
      <!---Hiding search form in nav bar:
        form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up!', new_user_registration_path %></li>
        <% end %>
        <!-- <li><a href="#">Link</a></li> -->
        <!---Hiding second of two dropdowns in nav bar:
        li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/places/edit.html.erb
<h1>Edit Your Place Details</h1>
<div class="booyah-box login-form col-xs-10 col-xs-offset-1">
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %><br>
    <%= f.input :address %><br>
    <%= f.input :description %><br>
    <%= f.submit 'Submit Your Edited Listing', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "nom_slider1.jpg", class: 'img-responsive' %>
      <div class="carousel-caption">
        Discover a world of great restaurants
      </div>
    </div>
    <div class="item">
      <%= image_tag "nom_slider2.jpg" %>
      <div class="carousel-caption">
        Preview unforgettable destinations
      </div>
    </div>
    <div class="item">
      <%= image_tag "nom_slider3.jpg" %>
      <div class="carousel-caption">
        Share your opinion, read others: each is unique!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1 class="placename"><%= link_to place.name, place_path(place) %></h1>
    <i class="address"><%= place.address %></i><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
        <span class="user-email"><%= place.user.email %></span>
    <% end %>

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.order(:id).last.humanized_rating %></b> . . .
          <% end %> 
          <%= place.comments.order(:id).last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>
<br />
<%= paginate @places %>

app/views/places/new.html.erb
<div class="booyah-box newplace-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %><br>
    <%= f.input :address %><br>
    <%= f.input :description %><br>
    <%= f.submit 'Submit Your Listing', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= @place.name %></h1>
    <h4><%= @place.address %></h4>
    <br/>
    <p><%= @place.description %></p>
    <% @place.photos.each do |photo| %>
      <%= image_tag photo.picture %><br />
      <%= photo.caption %>
    <% end %>

  <% if @place.latitude.present? && @place.longitude.present? %>

      <script>
        function initMap() {
          var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: myLatLng
          });

          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
          });
        }
      </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvpQhtV6zmk5BftNRrGj9NgdTYN2_sAhE&callback=initMap">
      </script>

    <div id="map"></div>
  <% end %>

    <div class="pull-right">
      <% if current_user && current_user == @place.user %>
           <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this place from the site?'}, class: 'btn btn-danger' %>
      <% end %>
    <br />
    </div>
    <br />

  <!-- Modal for COMMENTS ONLY -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title" id="myModalLabel">Comment on This Place</h3>
        </div>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <br />
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add Your Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>  
      </div>
    </div>
  </div>

<%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
  <%= f.input :picture %><br />
  <%= f.input :caption %><br />
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= f.submit "Upload the Selected Photo", class: 'btn btn-primary' %>
<% end %>

</div>

<div class="col-xs-10 col-xs-offset-1 com-margin">
  <h2 class="pull-left">Comments</h2>
 <% if current_user.present? %>
  <!-- Button trigger modal -->
    <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
    Add a comment
  </button>
</div>
  <% else %>
    <h2 class="logintocomm">&nbsp;&nbsp;(<%= link_to 'Log In', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %> to Comment)</h2>
  <% end %>

<div class="clear"></div>
<% @place.comments.each do |comment| %>
  <div class="col-xs-12 col-sm-6">
    <blockquote class="col-xs-10">
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> . . .
      <% end %> 
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<table style="width:50%">
  <thead>
      <tr>
          <th>Name</th>
          <th style="text-align:right;">Price</th>
          <th style="text-align:right;">Quantity</th>
      </tr>
  </thead>
  <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td style="text-align:right;"><%= number_to_currency product.price %></td>
            <td style="text-align:right;"><%= product.quantity %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="col-xs-2 avatar">
    <%= image_tag "user-brown.png" %>
  </div>

  <div class="col-xs-10">
    <h1>My User Profile</h1>
    <h3 class="username">Username: <%= @user.email %></h3>
    <h3>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
    <ul>
    <li><h3><%= @user.comments.count %> total comment(s)</h3></li>
    <li><h3><%= @user.comments.where(rating: '5_stars').count %> &starf;&starf;&starf;&starf;&starf; rating(s)</h3></li>
    </ul>
    <br />
  </div>
  <div class="clear"></div>
</div>

<h1 class="text-center mysubheads">My Comments</h1>
<hr class="myhrs"></hr>
<% @user.comments.each do |comment| %>
  <div class="col-xs-12 col-sm-6">
    <h2 class="text-center placename"><%= link_to comment.place.name, place_path(comment.place) %></h2>
     <blockquote>
       <% if comment.humanized_rating.present? %>
         <b><%= comment.humanized_rating %></b> . . .
       <% end %> 
       <%= comment.message %>
       <small><%= comment.user.email %></small>
      </blockquote>
  </div>
<% end %>

<div class="clear"></div>
<h1 class="text-center mysubheads">My Places</h1>
<hr class="myhrs"></hr>
<br />  
<% @user.places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
   <h1 class="placename"><%= link_to place.name, place_path(place) %></h1><br />
   <i><%= place.address %></i><br />
   <p><%= place.description %></p><br />

  <% if place.user.present? %>
    <small><%= place.user.email %></small>
  <% end %>

  <% if place.comments.present? %>
    <div class="col-xs=12">
      <blockquote>
         <% if place.comments.last.humanized_rating.present? %>
           <b><%= place.comments.last.humanized_rating %></b> . . .
         <% end %> 
         <%= place.comments.last.message %>
         <small><%= place.comments.last.user.email %></small>
      </blockquote>
    </div>
  <% end %>
 </div>
<% end %>